=== KualiCo/ce-tech-docs/hrmanifest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema"
     targetNamespace="https://github.com/rSmart/ce-tech-docs/tree/master/v1_0"
               xmlns="https://github.com/rSmart/ce-tech-docs/tree/master/v1_0"
             version="1.0"
  elementFormDefault="qualified">

  <xs:element name="hrmanifest">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="records">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="record" type="RecordType" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="schemaVersion" type="xs:decimal" use="required"/>
      <xs:attribute name="reportDate" type="xs:dateTime" use="required"/>
      <xs:attribute name="recordCount" type="xs:int" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="RecordType">
    <xs:sequence>
      <xs:element name="affiliations">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="affiliation" type="AffiliationType" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="addresses">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="address" type="AddressType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="names">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="NameType" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="phones">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="phone" type="PhoneType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="emails">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="email" type="EmailType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="kcExtendedAttributes" type="KCExtendedAttributesType" maxOccurs="1" minOccurs="0"/>
      <xs:element name="degrees">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="degree" type="DegreeDataType" maxOccurs="1" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="appointments">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="appointment" type="AppointmentDataType" maxOccurs="1" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="principalId" type="xs:string" use="required"/>
    <xs:attribute name="principalName" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="AffiliationType">
    <xs:attribute name="affiliationType" type="xs:string" use="required"/>
    <xs:attribute name="campus" type="xs:string" use="required"/>
    <xs:attribute name="employeeStatus" type="xs:string" use="required"/>
    <xs:attribute name="employeeType" type="xs:string" use="required"/>
    <xs:attribute name="baseSalaryAmount" type="xs:float" use="required"/>
    <xs:attribute name="primaryDepartment" type="xs:string" use="required"/>
    <xs:attribute name="employeeId" type="xs:string" use="required"/>
    <xs:attribute name="primaryEmployment" type="xs:boolean" default="false"/>
    <xs:attribute name="default" type="xs:boolean" default="false"/>
    <xs:attribute name="active" type="xs:boolean" default="true"/>
  </xs:complexType>

  <xs:complexType name="AddressType">
    <xs:attribute name="addressType" type="xs:string"/>
    <xs:attribute name="addressLine1" type="xs:string"/>
    <xs:attribute name="addressLine2" type="xs:string"/>
    <xs:attribute name="addressLine3" type="xs:string"/>
    <xs:attribute name="city" type="xs:string"/>
    <xs:attribute name="stateOrProvince" type="xs:string"/>
    <xs:attribute name="postalCode" type="xs:string"/>
    <xs:attribute name="country" type="xs:string"/>
    <xs:attribute name="default" type="xs:boolean" default="false"/>
    <xs:attribute name="active" type="xs:boolean" default="true"/>
  </xs:complexType>

  <xs:complexType name="NameType">
    <xs:attribute name="nameCode" type="xs:string" use="required"/>
    <xs:attribute name="prefix" type="xs:string"/>
    <xs:attribute name="firstName" type="xs:string" use="required"/>
    <xs:attribute name="lastName" type="xs:string" use="required"/>
    <xs:attribute name="suffix" type="xs:string"/>
    <xs:attribute name="default" type="xs:boolean" default="false"/>
    <xs:attribute name="active" type="xs:boolean" default="true"/>
  </xs:complexType>

  <xs:complexType name="PhoneType">
    <xs:attribute name="phoneType" type="xs:string"/>
    <xs:attribute name="phoneNumber" type="xs:string"/>
    <xs:attribute name="extension" type="xs:string"/>
    <xs:attribute name="country" type="xs:string"/>
    <xs:attribute name="default" type="xs:boolean" default="false"/>
    <xs:attribute name="active" type="xs:boolean" default="true"/>
  </xs:complexType>

  <xs:complexType name="EmailType">
    <xs:attribute name="emailType" type="xs:string"/>
    <xs:attribute name="emailAddress" type="xs:string"/>
    <xs:attribute name="default" type="xs:boolean" default="false"/>
    <xs:attribute name="active" type="xs:boolean" default="true"/>
  </xs:complexType>

  <xs:complexType name="KCExtendedAttributesType">
    <xs:attribute name="country" type="xs:string"/>
    <xs:attribute name="ageByFiscalYear" type="xs:int"/>
    <xs:attribute name="race" type="xs:string"/>
    <xs:attribute name="educationLevel" type="xs:string"/>
    <xs:attribute name="degree" type="xs:string"/>
    <xs:attribute name="major" type="xs:string"/>
    <xs:attribute name="handicapped" type="xs:boolean" default="false"/>
    <xs:attribute name="handicapType" type="xs:string"/>
    <xs:attribute name="veteran" type="xs:boolean" default="false"/>
    <xs:attribute name="veteranType" type="xs:string"/>
    <xs:attribute name="visa" type="xs:boolean" default="false"/>
    <xs:attribute name="visaType" type="xs:string"/>
    <xs:attribute name="visaCode" type="xs:string"/>
    <xs:attribute name="visaRenewalDate" type="xs:date"/>
    <xs:attribute name="officeLocation" type="xs:string"/>
    <xs:attribute name="secondaryOfficeLocation" type="xs:string"/>
    <xs:attribute name="school" type="xs:string"/>
    <xs:attribute name="yearGraduated" type="xs:string"/>
    <xs:attribute name="directoryDepartment" type="xs:string"/>
    <xs:attribute name="vacationAccrual" type="xs:boolean" default="false"/>
    <xs:attribute name="onSabbatical" type="xs:boolean" default="false"/>
    <xs:attribute name="idProvided" type="xs:string"/>
    <xs:attribute name="idVerified" type="xs:string"/>
    <xs:attribute name="citizenshipType" type="xs:int"/>
    <xs:attribute name="multiCampusPrincipalId" type="xs:string"/>
    <xs:attribute name="multiCampusPrincipalName" type="xs:string"/>
    <xs:attribute name="salaryAnniversaryDate" type="xs:date"/>
  </xs:complexType>

  <xs:complexType name="DegreeDataType">
    <xs:attribute name="degree" type="xs:string"/>
    <xs:attribute name="degreeType" type="xs:string"/>
    <xs:attribute name="graduationYear" type="xs:string"/>
    <xs:attribute name="fieldOfStudy" type="xs:string"/>
    <xs:attribute name="specialization" type="xs:string"/>
    <xs:attribute name="school" type="xs:string"/>
    <xs:attribute name="schoolId" type="xs:string"/>
    <xs:attribute name="schoolIdCode" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="AppointmentDataType">
    <xs:attribute name="unit" type="xs:string"/>
    <xs:attribute name="jobCode" type="xs:string"/>
    <xs:attribute name="appointmentType" type="xs:string"/>
    <xs:attribute name="salary" type="xs:float"/>
    <xs:attribute name="startDate" type="xs:date"/>
    <xs:attribute name="endDate" type="xs:date"/>
    <xs:attribute name="jobTitle" type="xs:string"/>
    <xs:attribute name="preferedJobTitle" type="xs:string"/>
  </xs:complexType>

</xs:schema>

=== KualiCo/ce-tech-docs/exampleImport.xml
<?xml version="1.0" encoding="UTF-8"?>
<hrmanifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="hrmanifest.xsd"
   submitterId="foo"
   transactionId="00001" 
   reportDate="2013-05-20T13:03:00.0" 
   recordCount="1">
  <records>
	  <record principalId="0001" principalName="jdoe">
	    <affiliations>
		    <affiliation affiliationType="affType"
		      campus="MN"
		      employeeStatus="ACTIVE"
		      employeeType="APPOINTED"
		      baseSalaryAmount="50180"
		      primaryDepartment="MATH"
		      employeeId="092001234"
		      primaryEmployment="true"
          default="true"
          active="true"
        />
		  </affiliations>
	    <addresses>
	      <address addressType="HOME" 
	        addressLine1="1234 E. Main St." 
	        addressLine2="Apt. 8C" 
	        city="Minneapolis" 
	        stateOrProvince="MN"
	        postalCode="34567"
	        country="US"
	        default="true"
	        active="true" />
	    </addresses>
	    <names>
	      <name nameCode="NAME"
	        prefix="Mr."
	        firstName="Jonathon"
	        lastName="Doe"
	        default="true"
	        active="true" />
	    </names>
	    <phones>
	      <phone phoneType="OFFICE"
	        phoneNumber="204-391-1101"
	        country="US"
	        default="true"
	        active="true" />
	      <phone phoneType="HOME"
	        phoneNumber="204-718-3221"
	        country="US"
	        active="true" />
	    </phones>
	    <emails>
	      <email emailType="WORK"
	        emailAddress="jdoe@university.edu"
	        default="true"
	        active="true" />
	    </emails>
	    <kcExtendedAttributes country="US"
	      ageByFiscalYear="52"
	      race="CAUCASIAN"
	      educationLevel="PHD"
	      degree="PHD"
	      major="MATHEMATICS"
	      handicapped="false"
	      veteran="true"
	      veteranType="A"
	      visa="false"
	      officeLocation="503 Carter Hall"
	      school="MATH"
	      yearGraduated="1983"
	      directoryDepartment="MATH"
	      vacationAccrual="true"
	      idProvided="John Doe"
	      idVerified="???"
	      citizenshipType="1"
	      salaryAnniversaryDate="2010-01-01"/>
	    <degrees>
		    <degree degree="PhD"
		      degreeType="GRAD"
		      graduationYear="1983"
		      fieldOfStudy="Mathematics"
		      specialization="non-linear algebra"
		      school="Texas A&amp;M University"
		      schoolId="1234"
		      schoolIdCode="UMN" />
	    </degrees>
	    <appointments>
		    <appointment unit="MATH"
		      jobCode="0010"
		      appointmentType="APP"
		      salary="50180"
		      startDate="2010-01-01"
		      jobTitle="Professor"
		      preferedJobTitle="Professor"/>
	    </appointments>
	  </record>
  </records>
</hrmanifest>

=== KualiCo/ce-tech-docs/hrExampleImport.xml
<?xml version="1.0" encoding="UTF-8"?>
<hrmanifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="https://github.com/rSmart/ce-tech-docs/tree/master/v1_0
                       https://raw.github.com/rSmart/ce-tech-docs/master/v1_0/hrmanifest.xsd"
                xmlns="https://github.com/rSmart/ce-tech-docs/tree/master/v1_0"
   schemaVersion="1.0"
   reportDate="2013-05-20T13:03:00"
   recordCount="1">
  <records>
    <record principalId="0001" principalName="jdoe">
      <affiliations>
        <affiliation affiliationType="FCLTY"
          campus="MN"
          employeeStatus="A"
          employeeType="P"
          baseSalaryAmount="50180"
          primaryDepartment="MATH"
          employeeId="092001234"
          primaryEmployment="true"
          default="true"
          active="true"
        />
      </affiliations>
      <addresses>
        <address addressType="HM"
          addressLine1="1234 E. Main St."
          addressLine2="Apt. 8C"
          city="Minneapolis"
          stateOrProvince="MN"
          postalCode="34567"
          country="US"
          default="true"
          active="true" />
      </addresses>
      <names>
        <name nameCode="PRM"
          prefix="Mr"
          firstName="Jonathon"
          lastName="Doe"
          default="true"
          active="true" />
      </names>
      <phones>
        <phone phoneType="WRK"
          phoneNumber="204-391-1101"
          country="US"
          default="true"
          active="true" />
        <phone phoneType="HM"
          phoneNumber="204-718-3221"
          country="US"
          active="true" />
      </phones>
      <emails>
        <email emailType="WRK"
          emailAddress="jdoe@university.edu"
          default="true"
          active="true" />
      </emails>
      <kcExtendedAttributes county="Maricopa"
        ageByFiscalYear="52"
        race="CAUCASIAN"
        educationLevel="PHD"
        degree="Doctor of Psychology"
        major="MATHEMATICS"
        handicapped="true"
        handicapType="TODO Need a better handicapType example"
        veteran="true"
        veteranType="A"
        visa="true"
        visaCode="TODO need a better visaCode example"
        visaType="TODO need a better visaType example"
        visaRenewalDate="2013-12-25"
        officeLocation="503 Carter Hall"
        secondaryOfficeLocation="88 Regan Hall"
        school="MATH"
        yearGraduated="1983"
        directoryDepartment="MATH"
        directoryTitle="Master of the Universe"
        primaryTitle="Leader of the Evil Horde"
        vacationAccrual="true"
        idProvided="John_Doe"
        idVerified="John_Doe_Verified"
        multiCampusPrincipalId="0002"
        multiCampusPrincipalName="jdoe2"
        onSabbatical="true"
        citizenshipType="1"
        salaryAnniversaryDate="2010-01-01"/>
      <degrees>
        <degree degree="PhD"
          degreeType="GRAD"
          graduationYear="1983"
          fieldOfStudy="Mathematics"
          specialization="non-linear algebra"
          school="Texas A&amp;M University"
          schoolId="1234"
          schoolIdCode="UMN" />
      </degrees>
      <appointments>
        <appointment unit="MATH"
          jobCode="0010"
          appointmentType="APP"
          salary="50180"
          startDate="2010-01-01"
          jobTitle="Professor"
          preferedJobTitle="Professor"/>
      </appointments>
    </record>
  </records>
</hrmanifest>

=== KualiCo/ce-tech-docs/v2_1/hrExampleImport.xml
<?xml version="1.0" encoding="UTF-8"?>
<hrmanifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="https://github.com/KualiCo/ce-tech-docs/tree/master/v2_1
                       https://raw.github.com/KualiCo/ce-tech-docs/master/v2_1/hrmanifest.xsd"
                xmlns="https://github.com/KualiCo/ce-tech-docs/tree/master/v2_1"
   schemaVersion="2.1"
   reportDate="2013-05-20T13:03:00"
   recordCount="1">
  <records>
    <record principalId="1234567890" principalName="jdoe">
      <affiliations>
        <affiliation affiliationType="FCLTY"
          campus="MN"
          default="true"
          active="true">
          <employment employeeStatus="A"
            employeeType="P"
            baseSalaryAmount="50180"
            primaryDepartment="MATH"
            employeeId="092001234"
            primaryEmployment="true"/>
        </affiliation>
      </affiliations>
      <addresses>
        <address addressTypeCode="HM"
          addressLine1="1234 E. Main St."
          addressLine2="Apt. 8C"
          city="Minneapolis"
          stateOrProvince="MN"
          postalCode="34567"
          country="US"
          default="true"
          active="true" />
      </addresses>
      <names>
        <name nameCode="PRM"
          prefix="Mr"
          firstName="Jonathon"
          middleName="R"
          lastName="Doe"
          default="true"
          active="true" />
      </names>
      <phones>
        <phone phoneType="WRK"
          phoneNumber="204-391-1101"
          country="US"
          default="true"
          active="true" />
        <phone phoneType="HM"
          phoneNumber="204-718-3221"
          country="US"
          active="true" />
      </phones>
      <emails>
        <email emailType="WRK"
          emailAddress="jdoe@university.email"
          default="true"
          active="true" />
      </emails>
      <kcExtendedAttributes county="Maricopa"
        ageByFiscalYear="52"
        race="CAUCASIAN"
        educationLevel="PHD"
        degree="M.Sc."
        major="MATHEMATICS"
        handicapped="true"
        handicapType="Olfactory"
        veteran="true"
        veteranType="A"
        visa="true"
        visaCode="TBD"
        visaType="TBD"
        visaRenewalDate="2013-12-25"
        officeLocation="503 Carter Hall"
        secondaryOfficeLocation="88 Regan Hall"
        school="MATH"
        yearGraduated="1983"
        directoryDepartment="MATH"
        directoryTitle="Master of the Universe"
        primaryTitle="Leader of the Evil Horde"
        vacationAccrual="true"
        idProvided="John_Doe"
        idVerified="John_Doe_Verified"
        multiCampusPrincipalId="0002"
        multiCampusPrincipalName="jdoe2"
        onSabbatical="true"
        citizenshipType="1"
        salaryAnniversaryDate="2010-01-01"/>
      <degrees>
        <degree degree="PhD"
          degreeCode="DD"
          graduationYear="1983"
          fieldOfStudy="Mathematics"
          specialization="non-linear algebra"
          school="Texas A&amp;M University"
          schoolId="1234"
          schoolIdCode="UMN" />
      </degrees>
      <appointments>
        <appointment unitNumber="SECED"
          jobCode="0010"
          appointmentType="1"
          salary="50180"
          startDate="2010-01-01"
          jobTitle="Professor"
          preferedJobTitle="Professor"/>
      </appointments>
    </record>
  </records>
</hrmanifest>
